apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingest-service
  labels:
    app: ingest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingest-service
  template:
    metadata:
      labels:
        app: ingest-service
    spec:
      containers:
        - name: ingest-service
          image: your-docker-repo/ingest-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: WOOCOMMERCE_API_URL
              valueFrom:
                secretKeyRef:
                  name: woocommerce-secrets
                  key: api_url
            - name: WOOCOMMERCE_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: woocommerce-secrets
                  key: consumer_key
            - name: WOOCOMMERCE_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: woocommerce-secrets
                  key: consumer_secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      imagePullSecrets:
        - name: regcred