apiVersion: apps/v1
kind: Deployment
metadata:
  name: segmentation-service
  labels:
    app: segmentation-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: segmentation-service
  template:
    metadata:
      labels:
        app: segmentation-service
    spec:
      containers:
        - name: segmentation-service
          image: your-docker-repo/segmentation-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database-url
            - name: WOOCOMMERCE_API_URL
              value: "https://your-woocommerce-store.com/wp-json/wc/v3/"
            - name: WOOCOMMERCE_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: woo-secret
                  key: consumer-key
            - name: WOOCOMMERCE_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: woo-secret
                  key: consumer-secret
      imagePullSecrets:
        - name: regcred